import rtconfig
from building import *

cwd = GetCurrentDir()

src = Glob('../applications/*.c') + Glob('../drivers/*.c') + Glob('../packages/nrf24l01-latest/demo/*.c') + Glob('../packages/nrf24l01-latest/src/*.c') + Glob('../libraries/STM32F1xx_HAL_Driver/Src/*.c') + Glob('../libraries/STM32F1xx_HAL_Driver/Src/Legacy/*.c') + Glob('../libraries/CMSIS/Device/ST/STM32F1xx/Source/Templates/*.c') + Glob('../libraries/CMSIS/Device/ST/STM32F1xx/Source/Templates/gcc/*.S') + Glob('../drivers/my_drv/hard_encoder/*.c') + Glob('../drivers/my_drv/motrol/*.c') + Glob('../drivers/my_drv/motrol_dir/*.c') + Glob('../applications/pid/*.c')

CPPPATH = [
	cwd,
	cwd + '/../applications',
	cwd + '/../drivers',
	cwd + '/../packages/nrf24l01-latest/src',
	cwd + '/../libraries/STM32F1xx_HAL_Driver/Inc',
	cwd + '/../libraries/STM32F1xx_HAL_Driver/Inc/Legacy',
	cwd + '/../libraries/CMSIS/Include',
	cwd + '/../libraries/CMSIS/RTOS/Template',
	cwd + '/../libraries/CMSIS/Device/ST/STM32F1xx/Include',
	cwd + '/../drivers/include',
	cwd + '/../drivers/my_drv/hard_encoder',
	cwd + '/../drivers/my_drv/motrol',
	cwd + '/../drivers/my_drv/motrol_dir',
	cwd + '/../drivers/include/config',
	cwd + '/../applications/pid',
	str(Dir('#'))
]

CPPDEFINES = [
	'SOC_FAMILY_STM32',
	'SOC_SERIES_STM32F1',
	'USE_HAL_DRIVER',
	'STM32F103xE',
	'c     ',
	'm     ',
]

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH, CPPDEFINES = CPPDEFINES)

Return('group')

